language: java

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "iGFpacAiqeg2jVeDL5dbh5w/TPg4okyfWKsYxonYqIPYUbwsyLyGUZULoWh7sK5GMDUPnhMLKAnKCphQO40zjnsnuO3imGqheeCoD1dIENr0fCSVYtEwkTJRePKRNEgGoIRs9/0qNSYLywkHBH53rsx2weXWn9FTNuhS9C8iwZ8="

addons:
  coverity_scan:
    project:
      name: "SALSA-W/M-SALSA"
      description: "Build submitted via Travis CI"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
  email: false