# enable build for java8 - not working with container-based infrastructure
sudo: required

language: java

jdk:
  - oraclejdk8
  
# http://binkley.blogspot.it/2015/10/struggling-with-travis-ci-and-maven-33.html
# TODO: Gross until Travis support setting maven version or upgrades to 3.3
before_install:
  - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
before_script:
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
script: mvn verify -Dgpg.skip=true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "W7hvytvGfZ+/YYUFQfAnCd1QKZ5CzMaI/vhRdEPgv2SBpW2stR8pWZDfCej42C9PycvOW8WSBg9wZAYuMBbj32OhMTbB1IFyV8M+sYw6ZE0B7tsQBQyA0K1epXHdKt3HPUiXK1ckzVK6KuK0ko9UBXbsBcoj2p2+Q6xyu/hSOug="

addons:
  coverity_scan:
    # GitHub project metadata
    project:
      name: "SALSA-W/M-SALSA"
    notification_email: m.salsa@scientist.com
    
    # Commands to prepare for build_command
    # ** likely specific to your build **
    build_command_prepend: "mvn clean"

    # The command that will be added as an argument to "cov-build" to compile your project
    build_command: "mvn -DskipTests=true compile"
    
    # Pattern to match selecting branches that will run analysis.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: master

script:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
  email: false